apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-go
  template:
    metadata:
      labels:
        app: kube-go
    spec:
      containers:
      - name: kube-go
        image: avs17/wb_go:v2
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "LOG_LEVEL"
          value: "PRODUCTION"
